### ISSUE TITLE
Possible ideas: JSON pointer style

### ISSUE THREAD

**Issue by nicola** [ipfs/ipld-examples#5]
I like the way JSON pointer was originally envisioned. The idea that one could navigate a json tree in the same way we navigate paths

```
{people: [{name: "Nicola"}, {name: "Juan"}]}

/people
>  [{name: "Nicola"}, {name: "Juan"}]}

/people/0
> {name: "Nicola"}

/people/0/name
> "Nicola"
```

I remember the original ipld notes alluded at this and I found this so interesting. The first three examples seem very similar to this. However, the only limitation is on how we would like to follow/resolve links..

```
{people: [{@mlink: "hash!?"}, ..]}
```

**Comment by rvagg** [comment]
closing for archival
